import type { BuildingAssetId, Team } from "../assets";
import {
  BASE_RESPAWN_SECONDS,
  DEFAULT_SKILL_LEVELS,
  RECALL_DURATION,
} from "../data/game-config";
import type { UnitKind } from "../types";
import type { Building, Unit } from "./types";

export const createHero = (id: string, assetId: string, team: Team, x: number, y: number): Unit => ({
  id,
  assetId,
  team,
  kind: "hero",
  x,
  y,
  hp: team === "azure" ? 1250 : 1180,
  maxHp: team === "azure" ? 1250 : 1180,
  mana: 560,
  maxMana: 560,
  shield: 0,
  level: 1,
  xp: 0,
  gold: team === "azure" ? 842 : 0,
  speed: 205,
  radius: 32,
  attackRange: 92,
  attackDamage: team === "azure" ? 112 : 106,
  buildingDamageMultiplier: 1,
  attackCooldown: 0.95,
  cooldownReduction: 0,
  attackTimer: 0,
  action: "idle",
  actionTimer: 0,
  lastDirection: team === "azure" ? "north-east" : "south-west",
  slowTimer: 0,
  slowMultiplier: 1,
  rootTimer: 0,
  markTimer: 0,
  hasteTimer: 0,
  hasteMultiplier: 1,
  shieldTimer: 0,
  recallTimer: 0,
  recallDuration: RECALL_DURATION,
  skillLevels: { ...DEFAULT_SKILL_LEVELS },
  skillPoints: 0,
  alive: true,
  respawnTimer: 0,
  respawnDuration: BASE_RESPAWN_SECONDS,
});

export const createMinion = (id: string, assetId: string, team: Team, kind: Exclude<UnitKind, "hero">, x: number, y: number, initialAttackTimer: number): Unit => {
  const caster = kind === "caster";
  const siege = kind === "siege";
  return {
    id,
    assetId,
    team,
    kind,
    x,
    y,
    hp: siege ? 720 : caster ? 250 : 320,
    maxHp: siege ? 720 : caster ? 250 : 320,
    mana: 0,
    maxMana: 0,
    shield: 0,
    level: 1,
    xp: 0,
    gold: 0,
    speed: siege ? 58 : caster ? 72 : 84,
    radius: siege ? 28 : 20,
    attackRange: siege ? 175 : caster ? 145 : 54,
    attackDamage: siege ? 58 : caster ? 34 : 42,
    buildingDamageMultiplier: siege ? 2.25 : 1,
    attackCooldown: siege ? 1.55 : caster ? 1.35 : 1.05,
    cooldownReduction: 0,
    attackTimer: initialAttackTimer,
    action: "move",
    actionTimer: 0,
    lastDirection: team === "azure" ? "north-east" : "south-west",
    slowTimer: 0,
    slowMultiplier: 1,
    rootTimer: 0,
    markTimer: 0,
    hasteTimer: 0,
    hasteMultiplier: 1,
    shieldTimer: 0,
    recallTimer: 0,
    recallDuration: 0,
    skillLevels: { q: 0, w: 0, e: 0, r: 0 },
    skillPoints: 0,
    alive: true,
    respawnTimer: 0,
    respawnDuration: 0,
  };
};

export const createBuilding = (id: string, assetId: BuildingAssetId, team: Team, type: "tower" | "core", x: number, y: number): Building => {
  const tower = type === "tower";
  return {
    id,
    assetId,
    team,
    type,
    x,
    y,
    hp: tower ? 3000 : 4200,
    maxHp: tower ? 3000 : 4200,
    attackRange: tower ? 520 : 0,
    attackDamage: tower ? 190 : 0,
    attackCooldown: 1,
    attackTimer: 0,
    attackFlash: 0,
    radius: tower ? 72 : 104,
  };
};
